###############################################################################
#                           KylianDev Config Docker                           #
###############################################################################
version: "3.1"

networks:
  container_one:
      ipam:
          driver: default
          config:
              - subnet: 172.28.0.0/16

services:
    db:
      image: mysql:5.7
      container_name: docker-symfony4-mysql
      volumes:
      - ./data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'root'          
      networks:
        container_one:
            ipv4_address: 172.28.1.3

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: docker-symfony4-phpmyadmin
      ports:
          - "8080:80"
      links:
          - db:db
      networks:
        container_one:
            ipv4_address: 172.28.1.4

    webserver:
      image: nginx:alpine
      container_name: docker-symfony4-webserver
      restart: always
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8001:80"
      links: 
        - db           
      networks:
        container_one:
            ipv4_address: 172.28.1.2

    php-fpm:
      build: phpdocker/php-fpm
      container_name: docker-symfony4-php-fpm
      restart: always
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      links:
        - db        
      depends_on:
        - db
      networks:
        container_one:
            ipv4_address: 172.28.1.1